---
name: hook_cmd
pack: st2_utils
description: "Collect params to execute remotely"
enabled: true
trigger:
    type: core.st2.webhook
    parameters:
        url: "netpro"       
action:
    ref: st2_utils.chain_cmd2file
    parameters:
        hosts: "{{trigger.body.hosts}}"
        username: "{{trigger.body.user}}"
        password: "{{trigger.body.pass}}"
        cmd: "{{trigger.body.cmd}}"