---
name: on_hello_event1
pack: st2_utils
description: Sample rule firing on st2_utils.event1.
enabled: true
trigger:
    type: st2_utils.event1
action:
    ref: hello_st2.my_linux-cmd
    parameters:
        hosts: "3.3.3.3,4.4.4.4"